# Generated by Django 4.1.2 on 2022-11-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_data_alter_jenis_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='asia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=50)),
                ('sks', models.IntegerField()),
                ('link_gbr', models.CharField(blank=True, max_length=150)),
                ('waktu_posting', models.DateTimeField(auto_now_add=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis')),
            ],
        ),
    ]
